services:
  mc-postgres:
    container_name: mc-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DBNAE
    volumes:
      - pgdata_vol:/var/lib/postgresql/data
    networks:
      - internal_network

  mc-api:
    container_name: mc-api
    image: mc-api:latest
    build: ./mc-api
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - mc-postgres
    networks:
      - internal_network
    volumes:
      - ./mc-api:/mc-api

networks:
  internal_network:

volumes:
  pgdata_vol:
