import type { Metadata } from "next";
import localFont from "next/font/local";
import { ConfigProvider } from 'antd';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden	`}
      >
        <ConfigProvider
          theme={{
            token: {
              colorText: "#FAFAFA",
              colorTextPlaceholder: "#70707B",
              colorPrimary: '#ec4899',
              colorSecondary: '#ef4444',
              colorBgBase: '#1a1b27',
              colorBorder: "#70707B",
              colorBorderSecondary:"#3F3F46",
              colorIcon: '#70707B'
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
