import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ConfigProvider, theme } from 'antd';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider
            theme={{
              token: {
                colorBgBase: '#021428',
                colorTextBase: '#ffffff',
                colorBorder: '#323333',
                colorPrimary: '#1677ff',
                colorBgHover: '#333333',
                colorBorderHover: '#555555',
                colorBgActive: '#444444',
                colorBorderActive: '#777777',
                colorPrimaryHover: '#3c9eff',
                colorPrimaryActive: '#0e5adb',
                colorSecondary: '#ff6f61',
              },
            }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
